package com.example.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
public class MainController {
	
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	
	@GetMapping(path="/")
	public @ResponseBody String index() {
		return "<h2>Home Page</h2>";
	}
	
	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewUser (@RequestParam String firstname ,@RequestParam String lastname, @RequestParam Integer age) 
	{
		  User n = new User();
		  n.setFirstname(firstname);
		  n.setLastname(lastname); 
		  n.setAge(age);
		  userRepository.save(n);
		      
		  return "Saved"; 
	 } 
	 
	 @GetMapping(path="/all")
	 public @ResponseBody Iterable<User> getAllUsers() {
		    // This returns a JSON or XML with the users
		 return userRepository.findAll();
	 }
	 
	 @GetMapping(path="/count")
	 public Long count() {
		 return userRepository.count();
	 }
	 
	 @DeleteMapping(path="/users/{id}")
	 public void delete(@PathVariable int id) {
		 int userId = id;
	     userRepository.deleteById(userId);
	 }

}
